CREATE TABLE IF NOT EXISTS Tutor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(255),
    sobrenome varchar(255),
    cpf varchar(11),
    sexo varchar(2),
    idade int,
    telefone varchar(15),
    endereco varchar(255),
    numero int,
    bairro varchar(255),
    cep varchar(10),
    cidade varchar(255),
    estado varchar(255)
);

CREATE TABLE IF NOT EXISTS Pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo varchar(11),
    raca varchar(255),
    nome varchar(255),
    sexo varchar(255),
    idade int,
    peso int,
    observacao varchar(255),
    tutor_id BIGINT,
    constraint FK_tutor_pet foreign key(tutor_id) references Tutor(id)
);

CREATE TABLE IF NOT EXISTS Estadia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada varchar(100),
    saida varchar(255),
    valorDiaria varchar(255),
    pet_id BIGINT,
    constraint FK_pet_estadia foreign key(pet_id) references Pet(id)
);